{
 "title": "Мониторинг Windows Server инфраструктуры",
 "description": "Данный дашборд визуализирует метрики хостов на Windows Server, полученные с помощью Prometheus + Windows Exporter.",
 "tags": [
  "Prometheus",
  "Windows Exporter"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Источник данных",
    "query": {
     "query": "label_values(windows_cs_hostname, job)"
    }
   },
   {
    "name": "hostname",
    "label": "Выбранный хост",
    "query": {
     "query": "label_values(windows_cs_hostname{job=~\"$job\"}, hostname)"
    }
   },
   {
    "name": "instance",
    "label": "IP-адрес",
    "query": {
     "query": "label_values(windows_cs_hostname{job=~\"$job\",hostname=~\"$hostname\"}, instance)"
    }
   },
   {
    "name": "show_hostname",
    "label": "Show the hostname used",
    "query": {
     "query": "label_values(windows_cs_hostname{job=~\"$job\",instance=~\"$instance\"}, hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Обзор ресурсов всех хостов", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Обзор ресурсов серверов",
   "type": "table",
   "description": "Таблица, содержащая основные параметры всех узлов. Позволяет быстро оценить состояние нескольких хостов.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "windows_os_info{job=~\"$job\"} * on(instance) group_right(product) windows_cs_hostname"
    },
    {
     "expr": "time() - windows_system_system_up_time{job=~\"$job\"}",
     "legendFormat": "Uptime"
    },
    {
     "expr": "windows_cs_logical_processors{job=~\"$job\"} - 0",
     "legendFormat": "CPU Cores"
    },
    {
     "expr": "avg by (instance) (windows_cpu_core_frequency_mhz{job=~\"$job\"})",
     "legendFormat": "CPU Frequency"
    },
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{job=~\"$job\",mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "CPU usage%"
    },
    {
     "expr": "windows_cs_physical_memory_bytes{job=~\"$job\"} - 0",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "100 - 100 * windows_os_physical_memory_free_bytes{job=~\"$job\"} / windows_cs_physical_memory_bytes{job=~\"$job\"}",
     "legendFormat": "Memory Usage%"
    },
    {
     "expr": "1 - (windows_logical_disk_free_bytes{job=~\"$job\",volume=~\"C:\"}/windows_logical_disk_size_bytes{job=~\"$job\",volume=~\"C:\"})",
     "legendFormat": "C:/ Drive Usage"
    },
    {
     "expr": "max by (instance) (1 - windows_logical_disk_free_bytes{job=~\"$job\", volume=~\".:\"}/windows_logical_disk_size_bytes{job=~\"$job\", volume=~\".:\"})",
     "legendFormat": "Partition Used%"
    },
    {
     "expr": "windows_system_processes{job=~\"$job\"}",
     "legendFormat": "Number of processes"
    },
    {
     "expr": "sum by (instance) (windows_service_state{job=~\"$job\",state=~\"running\"})",
     "legendFormat": "Running Services"
    }
   ]
  },
  {
   "title": "Использование CPU по хостам",
   "type": "timeseries",
   "description": "График, показывающий уровень использования CPU по каждому хосту за определённый период времени. Полезен для анализа нагрузки на процессоры.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{job=~\"$job\",mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Использование памяти по хостам",
   "type": "timeseries",
   "description": "График, отображающий процент использования оперативной памяти на каждом хосте. Помогает выявлять перегруженные серверы.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100.0 - 100 * windows_os_physical_memory_free_bytes{job=~\"$job\"} / windows_cs_physical_memory_bytes{job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Максимальный трафик сетевых интерфейсов по хостам",
   "type": "timeseries",
   "description": "Отображает максимальную скорость передачи данных для каждого хоста — как входящий, так и исходящий трафик.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "max by (instance) (irate(windows_net_bytes_sent_total{job=~\"$job\",nic!~\"(?i:(.*(isatap|VPN).*))\"}[2m]))*8",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}_Upload",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "-max by (instance) (irate(windows_net_bytes_received_total{job=~\"$job\",nic!~\"(?i:(.*(isatap|VPN).*))\"}[2m]))*8",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}_Download",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Максимальная скорость чтения/записи дисков по хостам",
   "type": "timeseries",
   "description": "Показывает интенсивность операций чтения и записи на дисках по каждому хосту. Полезно при анализе производительности дисковых подсистем.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "-max by (instance) (irate(windows_logical_disk_read_bytes_total{job=~\"$job\", volume=~\".:\"}[2m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}_Read",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "max by (instance) (irate(windows_logical_disk_write_bytes_total{job=~\"$job\", volume=~\".:\"}[2m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}_Write",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Максимальное количество операций ввода/вывода (IOPS) по хостам",
   "type": "timeseries",
   "description": "Отражает количество операций ввода-вывода в секунду (IOPS) для каждого хоста. Используется для диагностики проблем с дисками.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "-max by (instance) (irate(windows_logical_disk_reads_total{job=~\"$job\", volume=~\".:\"}[2m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}_Read",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "max by (instance) (irate(windows_logical_disk_writes_total{job=~\"$job\", volume=~\".:\"}[2m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}_Write",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Детальный мониторинг выбранного хоста: $show_hostname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Время работы",
     "type": "stat",
     "description": "Статистика, показывающая время, в течение которого система была активна. Позволяет оценить стабильность работы сервера.",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 20 },
     "repeat": "host",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - windows_system_boot_time_timestamp{job=~\"$job\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Использование CPU",
     "type": "gauge",
     "description": "Индикатор, отображающий текущий уровень использования процессора в процентах.",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - (avg(irate(windows_cpu_time_total{job=~\"$job\",instance=~\"$instance\",mode=\"idle\"}[2m])))*100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Использование RAM",
     "type": "gauge",
     "description": "Индикатор, отображающий текущий уровень использования оперативной памяти в процентах.",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - (windows_os_physical_memory_free_bytes{job=~\"$job\",instance=~\"$instance\"} / windows_cs_physical_memory_bytes{job=~\"$job\",instance=~\"$instance\"})*100"
      }
     ]
    },
    {
     "title": "Процент заполнения дисков",
     "type": "bargauge",
     "description": "Столбцы, отображающие степень использования каждого раздела диска на выбранном хосте.",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - (windows_logical_disk_free_bytes{job=~\"$job\", instance=~\"$instance\", volume=~\".:\"} / windows_logical_disk_size_bytes{job=~\"$job\", instance=~\"$instance\", volume=~\".:\"}) * 100",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "Количество ядер CPU",
     "type": "stat",
     "description": "Отображает число логических процессоров на выбранном хосте.",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 23 },
     "repeat": "host",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "windows_cs_logical_processors{job=~\"$job\",instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Общий объем RAM",
     "type": "stat",
     "description": "Отображает общий объем установленной оперативной памяти на сервере.",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 26 },
     "repeat": "host",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "windows_cs_physical_memory_bytes{job=~\"$job\",instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "График использования CPU",
     "type": "timeseries",
     "description": "Подробный график использования процессора во времени.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - avg(irate(windows_cpu_time_total{job=~\"$job\",instance=~\"$instance\",mode=\"idle\"}[5m]))*100",
       "legendFormat": "CPU usage"
      }
     ]
    },
    {
     "title": "График использования RAM",
     "type": "timeseries",
     "description": "График, отображающий физическую и виртуальную память (общую и свободную). Полезно для анализа потребления памяти.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "windows_cs_physical_memory_bytes{job=~\"$job\",instance=~\"$instance\"}",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Total Physical Memory",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "windows_os_physical_memory_free_bytes{job=~\"$job\",instance=~\"$instance\"}",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Physical Memory Remaining",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "windows_os_virtual_memory_bytes{job=~\"$job\",instance=~\"$instance\"}",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Virtual Memory",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "expr": "windows_os_virtual_memory_free_bytes{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "Free Virtual Memory"
      }
     ]
    },
    {
     "title": "График использования сети",
     "type": "timeseries",
     "description": "График, отображающий процент использования пропускной способности сетевых интерфейсов.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "round((irate(windows_net_bytes_total{job=~\"$job\",instance=~\"$instance\",nic!~\"(?i:(.*(isatap|VPN).*))\"}[5m]) * 8 / (windows_net_current_bandwidth_bytes{job=~\"$job\",instance=~\"$instance\",nic!~\"(?i:(.*(isatap|VPN).*))\"} * 8)) * 100)",
       "legendFormat": "{{nic}}"
      }
     ]
    },
    {
     "title": "Свободное место на диске",
     "type": "timeseries",
     "description": "График, отображающий объем свободного места на каждом разделе диска. Предупреждает о возможной нехватке дискового пространства.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "windows_logical_disk_free_bytes{job=~\"$job\",instance=~\"$instance\", volume=~\".:\"}",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Space remaining {{volume}}",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "windows_logical_disk_size_bytes{job=~\"$job\",instance=~\"$instance\", volume=~\".:\"}",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Total Space {{volume}}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Чтение и запись на дисках",
     "type": "timeseries",
     "description": "Графики, отображающие скорость чтения и записи данных с дисков. Помогает анализировать производительность дисковой подсистемы.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "irate(windows_logical_disk_read_bytes_total{job=~\"$job\",instance=~\"$instance\", volume=~\".:\"}[5m])",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Read {{volume}}",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "irate(windows_logical_disk_write_bytes_total{job=~\"$job\",instance=~\"$instance\", volume=~\".:\"}[5m])",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Write {{volume}}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Операции ввода-вывода на дисках",
     "type": "timeseries",
     "description": "Графики, отображающие количество операций чтения и записи на дисках в секунду (IOPS).",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "irate(windows_logical_disk_reads_total{job=~\"$job\",instance=~\"$instance\", volume=~\".:\"}[5m])",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "read {{volume}}",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "irate(windows_logical_disk_writes_total{job=~\"$job\",instance=~\"$instance\", volume=~\".:\"}[5m])",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "write {{volume}}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Детальный график сетевого трафика",
     "type": "timeseries",
     "description": "Графики, отображающие входящий и исходящий сетевой трафик по каждому сетевому адаптеру. Полезно для диагностики сетевых проблем.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "irate(windows_net_bytes_sent_total{job=~\"$job\",instance=~\"$instance\",nic!~\"(?i:(.*(isatap|VPN).*))\"}[5m]) * 8 > 0",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "{{nic}}-Sent-Upload",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "irate(windows_net_bytes_received_total{job=~\"$job\",instance=~\"$instance\",nic!~\"(?i:(.*(isatap|VPN).*))\"}[5m]) * 8",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "{{nic}}-Received-Download",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Сетевые ошибки и отброшенные пакеты",
     "type": "timeseries",
     "description": "График, отображающий количество отброшенных или поврежденных сетевых пакетов. Полезно для диагностики сетевых проблем.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "irate(windows_net_packets_outbound_discarded_total{job=~\"$job\",instance=~\"$instance\", nic!~\"(?i:(.*(isatap|VPN).*))\"}[5m]) + irate(windows_net_packets_outbound_errors_total{job=~\"$job\",instance=~\"$instance\"}[5m])",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "{{nic}}_outbound",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "irate(windows_net_packets_received_discarded_total{job=~\"$job\",instance=~\"$instance\", nic!~\"(?i:(.*(isatap|VPN).*))\"}[5m]) + irate(windows_net_packets_received_errors_total{job=~\"$job\",instance=~\"$instance\"}[5m])",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "{{nic}}_received",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Состояние служб",
     "type": "timeseries",
     "description": "График, показывающий количество сервисов в различных состояниях (работают, остановлены и т.д.). Помогает контролировать доступность системных сервисов.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "sum(windows_service_state{job=~\"$job\",instance=~\"$instance\"}) by (state)",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "{{state}}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Системные потоки",
     "type": "timeseries",
     "description": "График, отображающий количество активных потоков в системе. Помогает отслеживать общую нагрузку на ядро ОС.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "windows_system_threads{job=~\"$job\",instance=~\"$instance\"}",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "System Threads",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Количество процессов",
     "type": "timeseries",
     "description": "График, отображающий количество активных процессов на сервере. Может использоваться для анализа нагрузки.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "windows_system_processes{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "Number of processes"
      }
     ]
    },
    {
     "title": "График системных исключений",
     "type": "timeseries",
     "description": "График, отображающий количество исключений (ошибок), возникающих в системе. Может быть полезен для диагностики программных сбоев.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "irate(windows_system_exception_dispatches_total{job=~\"$job\",instance=~\"$instance\"}[5m])",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Exceptions",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    }
   ]
  }
 ]
}